// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/4/2025, 6:10:09 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Volumes/Untitled/dev/jangid/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/plugins/**/*.{js,ts,mjs}","/Volumes/Untitled/dev/jangid/apps/web/composables/**/*.{js,ts,mjs}","/Volumes/Untitled/dev/jangid/apps/web/utils/**/*.{js,ts,mjs}","/Volumes/Untitled/dev/jangid/apps/web/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Volumes/Untitled/dev/jangid/apps/web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;